networks:
 inception-network:
  name: inception-network
  driver: bridge

services:

 mariadb:
  image: inception:mariadb
  container_name: mariadb
  build:
   context: ./requirements/mariadb
   dockerfile: Dockerfile
  env_file:
   - .env
  volumes:
   - mariadb:/var/lib/mysql:rw
  expose:
   - "3306"
  networks:
   - inception-network
  restart: always

 wordpress:
  image: inception:wordpress
  container_name: wordpress
  build:
   context: ./requirements/wordpress
   dockerfile: Dockerfile
  volumes:
   - wordpress:/var/www/wordpress:rw
  env_file:
   - .env
  expose:
   - "9000"
  networks:
   - inception-network
  restart: always

 nginx:
  image: inception:nginx
  container_name: nginx
  build:
   context: ./requirements/nginx
   dockerfile: Dockerfile
  volumes:
   - wordpress:/var/www/wordpress:rw
  env_file:
   - .env
  ports:
   - '443:443'
  networks:
   - inception-network
  restart: always
  depends_on:
   - wordpress

volumes:
 wordpress:
  name: wordpress
  driver: local
  driver_opts:
   type: volume
   device: $HOME/data/wordpress
   o: bind

 mariadb:
  name: mariadb
  driver: local
  driver_opts:
   type: volume
   device: $HOME/data/mariadb
   o: bind
