version: "3.9"

volumes:
  mariadb:
    driver: local                                   # save in local
    driver_opts:
      type: none                                    # no specific type
      o: bind                                       # bind mounts
      device: ${USER_HOME}/data/mariadb             # where to save volume in local
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${USER_HOME}/data/wordpress


networks:
  inception:
    driver: bridge
    name: inception      # allow the 3 containers to communicate


services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    restart: on-failure
    depends_on:
      - mariadb
    expose:
      - "9000"
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    restart: on-failure                     # restart in case of crash
    depends_on:                             # wait for wordpress to start nginx
      - wordpress
    ports:
      - "443:443"